name: StreamScreenToMap
version: 0.0.1
author: Ethann8
description: A plugin to be stream to map in minecraft.
api-version: 1.13
main: ch.shkermit.Main
commands:
  generateScreen:
    description: Generate Screen to Map
    usage: /generateScreen <width> <height>
    permission: streamscreen.map